mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis_config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
